# fly.toml app configuration file generated for calamoni on 2023-11-13T21:35:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "calamoni"
primary_region = "ams"
kill_timeout = 120

[env]
  AWS_DEFAULT_REGION="auto"
  R2_BUCKET_NAME="calamoni"


[[services]]
  protocol = "tcp"
  internal_port = 7777
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 7777

  [[services.tcp_checks]]
    grace_period = "60s"
    interval = "30s"
    timeout = "10s"

[mounts]
  source="data"
  destination="/data"
